pipeline:
  identifier: Build_ashfaq11_employee_1715681047392
  name: Build employee
  orgIdentifier: default
  projectIdentifier: employee_ci
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: ashfaq11/employee
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: RunTests
                  name: RunTests_1
                  identifier: RunTests_1
                  spec:
                    language: Java
                    buildTool: Maven
                    args: clean test
                    runOnlySelectedTests: true
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - "**/*.xml"
                    enableTestSplitting: false
