pipeline:
  identifier: Build_ashfaq11_employee_1715685676768
  name: Build employee
  orgIdentifier: default
  projectIdentifier: employee_ci
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: ashfaq11/employee
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo helloworld
